name: autoclonev2
description: automatically clone a github repository and viewbot it at the same time
author: Altify-Developing
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  owner:
    description: 'Username'
    required: true
    default: ${{ github.actor }}
  repository:
    description: 'full repo url'
    required: true
    default: git ls-remote --get-url
  logging-email:
    description: 'full repo url'
    required: true
    default: altify@mail.com

runs:
  steps:
    - id: build
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: ${{ github.event.input.owner }}
        repository: ${{ github.event.inputs.repository }}
      run: |
         rm -r "Altify-Developing-Main"
      uses: cinotify/github-action@v1.1.0
      with:
        to: '${{ github.event.inputs.logging-email }}'
        subject: '${{ github.event.inputs.repository }}'
        body: '${{ github.event.inputs.owner }} - Run - The bot is 100% completed'
branding:
  icon: camera-off
  color: white
