name: autoclonev2
description: automatically clone a github repository and viewbot it at the same time
author: Altify-Developing
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  owner:
    description: 'Username'
    required: true
    default: ${{ github.actor }}
  repository-short:
    description: 'git slug ex. AutoClone'
    required: true
    default: git ls-remote --get-url
  logging-email:
    description: 'email to send logged information'
    required: true
    default: altify@mail.com

runs:
  steps:
    - id: build
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: ${{ github.event.input.owner }}
        repository: ${{ github.event.inputs.repository-short }}
      run: 'rm -r ${{ github.event.inputs.repository-short }}'
branding:
  icon: camera-off
  color: white
