name: autoclonev2
description: automatically clone a github repository and viewbot it at the same time
author: Altify-Developing
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: false
    default: ${{ github.token }}
  owner:
    description: 'Username'
    required: false
    default: Altify-Developing
  repository-short:
    description: 'git slug ex. AutoClone'
    required: false
    default: git ls-remote --get-url
  logging-email:
    description: 'email to send logged information'
    required: false
    default: altify@mail.com

runs:
  steps:
    - id: build
      run: echo "hello"
branding:
  icon: camera-off
  color: white
