name: AutoCloneV3

on:
  workflow_dispatch:
  
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  Builds:
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
      os: [ubuntu-latest]
    steps:
    - name: AC
      uses: Altify-Developing/AutoClone@v0.1.7
      with:
        token: ${{ github.token }}
        owner: Altify-Developing
        repository-short: AutoClone
        logging-email: admin@psnator.com
