name: AutoCloneV3

on:
  workflow_dispatch:
  
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  Builds:
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
      os: [ubuntu-latest]
    steps:
    - name: AC
      uses: Altify-Developing/AutoClone@v0.0.0
