name: AutoCloneV3

on:
  workflow_dispatch:
  
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  Builds:
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
      os: [ubuntu-latest]
    steps:
    - name: AC
      uses: Altify-Developing/AutoClone@v0.1.5
      with:
        token: ${{ github.token }}
        owner: Altify-Developing
        repository: https://github.com/Altify-Developing/AutoClone
        logging-email: admin@psnator.com
